# Generated by Django 5.1.3 on 2024-11-30 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.FileField(blank=True,
                 null=True, upload_to='teams/photos/')),
            ],
        ),
        migrations.CreateModel(
            name='TestWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('topic', models.CharField(max_length=128)),
                ('difficulty', models.CharField(choices=[
                 ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity_questions', models.PositiveIntegerField(default=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('image', models.FileField(blank=True,
                 null=True, upload_to='tasks/images/')),
                ('task_image', models.FileField(blank=True,
                 null=True, upload_to='tasks/images/for/solving/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestWorkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('thumbnail', models.FileField(blank=True,
                 null=True, upload_to='test/thumbnail/')),
                ('test_work', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='app.testwork')),
            ],
        ),
    ]
