# Generated by Django 5.1.3 on 2024-12-01 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_testworkresult_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='testworkresult',
            name='team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.teammember'),
        ),
    ]
