# Generated by Django 5.1.3 on 2024-12-01 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_testworkresult_team_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='persmission',
            field=models.ManyToManyField(blank=True, through='app.TeamMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
