# Generated by Django 5.1.3 on 2024-12-01 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_team_persmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='persmission',
        ),
    ]
