# Generated by Django 5.1.3 on 2024-12-01 17:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_team_persmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestWork',
            new_name='TestWorkRequest',
        ),
        migrations.RenameModel(
            old_name='TestWorkResult',
            new_name='TestWorkResponse',
        ),
    ]
