# Generated by Django 5.1.3 on 2024-12-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_testwork_testworkrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.FileField(blank=True, help_text='Image to task', null=True, upload_to='tasks/images/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_image',
            field=models.FileField(blank=True, help_text='The image to solve', null=True, upload_to='tasks/images/for/solving/'),
        ),
    ]
