# Generated by Django 5.1.3 on 2024-12-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_task_image_alter_task_task_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestForUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('test_response', models.ManyToManyField(blank=True, related_name='tests_for_user', to='app.testworkresponse')),
            ],
        ),
    ]
