# Generated by Django 5.1.3 on 2024-12-01 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_testforuser_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testforuser',
            name='test_response',
        ),
        migrations.RemoveField(
            model_name='testforuser',
            name='user',
        ),
        migrations.AddField(
            model_name='testforuser',
            name='test_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_for_user', to='app.testworkresponse'),
        ),
        migrations.AddField(
            model_name='testforuser',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='tests_for_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
