# Generated by Django 5.1.3 on 2024-12-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_testforuser_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testforuser',
            name='test_response',
        ),
        migrations.AddField(
            model_name='testforuser',
            name='test_response',
            field=models.ManyToManyField(blank=True, related_name='tests_for_user', to='app.testworkresponse'),
        ),
    ]
