# Generated by Django 5.1.3 on 2024-12-01 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_testforuser_test_response'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testworkresponse',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='testworkresponse',
            name='team',
        ),
        migrations.RemoveField(
            model_name='testworkresponse',
            name='team_member',
        ),
        migrations.RemoveField(
            model_name='testworkresponse',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='testworkresponse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testforuser',
            name='user',
        ),
        migrations.AddField(
            model_name='testforuser',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
