# Generated by Django 5.1.3 on 2024-12-01 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_testworkresponse_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testforuser',
            name='user',
        ),
        migrations.AddField(
            model_name='testforuser',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
