# Generated by Django 5.1.3 on 2024-12-01 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_testforuser_user_testforuser_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testforuser',
            name='test_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.testworkresponse'),
        ),
    ]
