# Generated by Django 5.1.3 on 2024-12-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_testworkresponse_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='testworkresponse',
            name='count_questions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
