# Generated by Django 5.1.3 on 2024-12-03 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_answertest_number_of_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testforuser',
            name='is_completed',
        ),
    ]
