# Generated by Django 5.1.3 on 2024-12-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_testforuser_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertest',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
