# Generated by Django 5.1.3 on 2024-12-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_testforuser_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testforuser',
            name='answer',
        ),
    ]
