# Generated by Django 5.1.3 on 2024-12-03 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_testforuser_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertest',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.testworkresponse'),
        ),
    ]
