# Generated by Django 5.1.3 on 2024-12-03 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_answertest_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertest',
            name='test_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.testforuser'),
        ),
    ]
