# Generated by Django 5.1.3 on 2024-12-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_answertest_test_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answertest',
            old_name='test_user',
            new_name='test_for_user',
        ),
    ]
