# Generated by Django 5.1.3 on 2024-12-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_rename_test_user_answertest_test_for_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answertest',
            name='test_for_user',
        ),
    ]
