# Generated by Django 5.1.3 on 2024-12-03 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_task_team_team_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
