# Generated by Django 5.1.3 on 2024-12-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_task_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='testworkrequest',
            name='form_class',
            field=models.CharField(blank=True, choices=[('7', '7 клас'), ('8', '8 клас'), ('9', '9 клас')], default='7', max_length=128, null=True),
        ),
    ]
