# Generated by Django 5.1.3 on 2024-11-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_leader',
            field=models.BooleanField(default=False, verbose_name='Leader'),
        ),
    ]
