# Generated by Django 5.1.3 on 2024-11-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_is_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pupil_form',
        ),
        migrations.AddField(
            model_name='customuser',
            name='form_pupil',
            field=models.CharField(choices=[('7 form', '7'), ('8 form', '8'), ('9 form', '9')], default='7 form', max_length=10, verbose_name='Form'),
        ),
    ]
