# Generated by Django 5.1.3 on 2024-11-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_pupil_form_customuser_form_pupil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='form_pupil',
            field=models.CharField(choices=[('7', '7 клас'), ('8', '8 клас'), ('9', '9 клас')], default='7 form', max_length=10, verbose_name='Form'),
        ),
    ]
