# Generated by Django 5.1.3 on 2025-01-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_form_pupil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='form_pupil',
            field=models.CharField(choices=[('7', '7 клас'), ('8', '8 клас'), ('9', '9 клас')], default='7', max_length=10, verbose_name='Form'),
        ),
    ]
